export const strings = {
  MessageUnknownCredentials: "Identifiant ou mot de passe Inconnu",
  MessageQuitAsk: 'Voulez-vous quitter ?',
  URLShowcaseWebsite: 'https://www.pratic-boutic.fr/',
  MsgEmailAlreadyUsed: 'Le courriel que vous avez entré est déjà utilisé',
  MessageCodeMismatch: 'Le code sur le formulaire et celui envoyé par courriel ne correspondent pas',
  NoActiveSubscription: 'Il n y\'a pas d\'abonnement actif',
  MntCmdMiniErr: 'La commande n\'a pas atteint le niveau minimun. Impossible de poursuivre.',
  RequireCGV: 'Vous devez valider les Conditions générales de vente pour continuer.',
  NoBoutic: 'Il n\'y a pas de boutic avec cette alias',
  ErrConnect: 'Erreur de connexion',
  CantContinue: 'Impossible de continuer',
  NoAboChoosen: 'Erreur abonnement non choisi',
  BouticAlreadytaken: 'Problème d\'unicité : Ce nom de boutic est déjà utilisé',
  Congrats: 'Congratulations! Nous vous redirigeons vers votre compte.',
  BouticMade: 'Votre Boutic a été créée',
  NoPrice: 'Pas de tarifs',
  PassordDiffer: 'Le mots de passe et sa confirmation ne coincide pas',
  AskCancelSubscription: 'Voulez-vous annuler cet abonnement ?',
  Error: 'Erreur',
  Pbsendingbackpwd: 'Problème lors du renvoi du mot de passe',
  PwdSending: 'Envoi du mot de passe',
  NewMsgPwd: 'Un email vous a été envoyé avec le nouveau mot de passe.',
  NotInZone: 'Vous n\'êtes pas situé dans notre zone de livraison, vous devez venir chercher votre commande à notre boutique ',
  InvalidCredentials: "Identifiant ou mot de passe non-valide",
  MsgEmailInvalid: 'Le courriel que vous avez entré est invalide',
  MsgCodeInvalid: 'Le code que vous avez entré est invalide',
  // Ajoutez autant de chaînes de caractères que nécessaire
};